language: c

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j 2
  - make -j 2 test

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang
